# Generated by Django 4.2.7 on 2023-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0002_remove_taskcategory_tasks'),
        ('task_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='task_category.taskcategory'),
        ),
    ]
