# Generated by Django 4.2.7 on 2023-12-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='tasks',
        ),
    ]
